# Generated by Django 6.0.5 on 2026-08-29 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoundPetReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finder_name', models.CharField(max_length=100)),
                ('finder_phone', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('RESOLVED', 'Resolved')], default='NEW', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='found_reports', to='pets.pet')),
            ],
        ),
    ]
