# Generated by Django 6.0.5 on 2026-08-29 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_foundpetreport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FoundPetReport',
        ),
    ]
