# Generated by Django 6.0.5 on 2026-08-29 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerprofile',
            name='area',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ownerprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
